[package]
name = "parser"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
lexer.workspace = true
tracing.workspace = true
visibility.workspace = true

[features]
integration-tests = []



