[package]
name = "parser"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
lexer.workspace = true
tracing.workspace = true
visibility.workspace = true

rustc-hash = "1.1.0"
salsa = "0.17.0-pre.2"

[features]
integration-tests = []



