[package]
name = "lexer"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
visibility.workspace = true

finl_unicode = "1.2.0"

[features]
integration-tests = []

